default_language_version:
  python: python3.9
repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: stable
    hooks:
      - id: flake8
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
  - repo: https://github.com/asottile/seed-isort-config
    rev: stable
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: stable
    hooks:
      - id: isort
