version: "3.9"
services:
    client:
        build:
            context: .
            dockerfile: Dockerfile
        tty: true
        ports:
            - "3000:3000"
        volumes:
            - .:/app
            - /app/node_modules
        networks:
            - frontend
    mongodb:
        image: mongo
        container_name: mongo
        restart: unless-stopped
        command: mongod --auth
        environment:
            MONGO_INITDB_ROOT_USERNAME: "root"
            MONGO_INITDB_ROOT_PASSWORD: "password"
            MONGO_INITDB_DATABASE: webapp
            MONGODB_DATA_DIR: /data/db
        volumes:
            - mongodb:/data/db
        networks:
            - backend
networks:
   frontend: # communication between the React and Flask API containers
      driver: bridge
   backend: # communication between the MongoDB and the Flask API
      driver: bridge
volumes:
   mongodb:
      driver: local
   app:
      driver: local
