version: "3.9"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/api
      - /api/node_modules
    networks:
      - frontend
    depends_on:
      - db
  db:
    image: "mariadb:latest"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "aramgg"
    networks:
      - backend
    ports:
    - "3306:3306"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 app:app
    ports:
      - "5000:5000"
    volumes:
      - app:/var/www/
    depends_on:
      - db
    networks:
      - frontend
      - backend
networks:
  frontend: # communication between the React and Flask API containers
    driver: bridge
  backend: # communication between the MongoDB and the Flask API
    driver: bridge
volumes:
  app:
    driver: local
