version: "3.9"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/aramgg
      - /aramgg/node_modules
    networks:
      - frontend
    depends_on:
      - db
  db:
    container_name: postgres
    image: "postgres:latest"
    environment:
      POSTGRES_DB : "aramgg"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - backend
    volumes:
    - db_volume:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - app:/var/www/
    depends_on:
      - db
    networks:
      - frontend
      - backend
networks:
  frontend: # communication between the React and Flask API containers
    driver: bridge
  backend: # communication between the MongoDB and the Flask API
    driver: bridge
volumes:
  app:
    driver: local
  db_volume:
