version: "3.9"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/frontend
      - ./node_modules:/frontend/node_modules
    networks:
      - frontend
    depends_on:
      - db
      - api
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_DB : "aramgg"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    restart: on-failure
    networks:
      - backend
    volumes:
    - db_volume:/var/lib/postgresql/data
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
    depends_on:
      - db
    networks:
      - frontend
      - backend
    links:
      - db:db
    environment:
      - PYTHONUNBUFFERED=0
networks:
  frontend: # communication between the React and Django API containers
    driver: bridge
  backend: # communication between the PostgreSQL and the Django API
    driver: bridge
volumes:
  app:
    driver: local
  db_volume:
