# Generated by Django 3.1.7 on 2021-03-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Champion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("champion_id", models.IntegerField(max_length=30)),
                ("win", models.IntegerField(default=0)),
                ("loss", models.IntegerField(default=0)),
                ("kill", models.IntegerField(default=0)),
                ("death", models.IntegerField(default=0)),
                ("assist", models.IntegerField(default=0)),
                ("total_damage_done", models.IntegerField(default=0)),
                ("total_damage_taken", models.IntegerField(default=0)),
                ("total_healing_done", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=40, unique=True)),
                ("level", models.IntegerField()),
                ("profile_icon", models.IntegerField()),
                ("last_updated", models.BigIntegerField(blank=True, null=True)),
                ("account_id", models.CharField(max_length=100)),
                ("champion", models.ManyToManyField(to="aramgg.Champion")),
            ],
        ),
    ]
