# Generated by Django 3.1.7 on 2021-03-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aramgg", "0002_auto_20210305_1554"),
    ]

    operations = [
        migrations.AddField(
            model_name="champion",
            name="total_game_length",
            field=models.IntegerField(default=0),
        ),
    ]
