# Generated by Django 3.1.7 on 2021-03-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aramgg", "0003_champion_total_game_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="champion",
            name="num_double_kill",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="champion",
            name="num_legendary_kill",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="champion",
            name="num_penta_kill",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="champion",
            name="num_quadra_kill",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="champion",
            name="num_triple_kill",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="champion",
            name="total_gold_spent",
            field=models.IntegerField(default=0),
        ),
    ]
