# Generated by Django 3.1.7 on 2021-03-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aramgg", "0004_auto_20210308_0255"),
    ]

    operations = [
        migrations.AddField(
            model_name="champion",
            name="largest_killing_spree",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="champion",
            name="total_gold_earned",
            field=models.IntegerField(default=0),
        ),
    ]
